   package com.example.spring_boot_jdbc_app.security;                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                     
   import org.springframework.beans.factory.annotation.Autowired;
   import org.springframework.security.core.userdetails.UserDetails;                                                                                                                                                                                                                 
   import org.springframework.security.core.userdetails.UserDetailsService;
   import org.springframework.security.core.userdetails.UsernameNotFoundException;                                                                                                                                                                                                            
   import org.springframework.stereotype.Service;

   import com.example.spring_boot_jdbc_app.model.User;                                                                                                                                                                                                                               
   import com.example.spring_boot_jdbc_app.repository.UserRepository;                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                     
   @Service                                                                                                                                                                                                                                                                          
   public class MyUserDetailsService implements UserDetailsService {                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                     
       @Autowired                                                                                                                                                                                                                                                                    
       private UserRepository userRepository;                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                     
       /**                                                                                                                                                                                                                                                                           
        * Loads user details by email.                                                                                                                                                                                                                                               
        * - If the user exists: returns UserDetails with account details.                                                                                                                                                                                                            
        * - If the user does NOT exist: throws UsernameNotFoundException (expected).                                                                                                                                                                                                 
        * - If a database/system error occurs: propagates the exception for logging                                                                                                                                                                                                  
        *   and alerting (e.g., DB down, connection lost, constraint violation).                                                                                                                                                                                                     
        */                                                                                                                                                                                                                                                                           
       @Override                                                                                                                                                                                                                                                                     
       public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {                                                                                                                                                                                        
           // Direct call — let exceptions bubble up naturally                                                                                                                                                                                                                       
           User user = userRepository.getUserByEmail(email);                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                     
           if (user == null) {                                                                                                                                                                                                                                                       
               throw new UsernameNotFoundException("User not found with email: " + email);                                                                                                                                                                                           
           }                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                     
           return new MyUserDetails(user);                                                                                                                                                                                                                                           
       }                                                                                                                                                                                                                                                                             
   }    